name: image-choose # 工作流的名称
permissions:
  contents: write
on: # 触发条件
  # 手动触发
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'quark目录'
        required: true
        default: 'GLD'
        type: choice
        options:
          - GLD   # 黄金
          - SIL   # 白银


jobs: # 定义工作流中的作业
  image-choose:
    runs-on: ubuntu-latest # 指定运行作业的虚拟机环境，这里是最新版的Ubuntu
    steps:

      - name: Install Fonts 中文字体安装
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk  # 思源黑体

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Clear matplotlib cache
        run: |
          rm -rf ~/.cache/matplotlib

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug fonts
        run: |
          fc-list | grep -i noto | head -n 10


      - name: 执行商业图片选取
        env:

          # 其他配置
          LOG_LEVEL: INFO
          DATA_DAYS: 60
          MAX_CONCURRENT: 3

          PYTHONPATH: ${{ github.workspace }}

        run: |
          echo "=========================================="
          echo "时间: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          echo "=========================================="
#          获取quark目录
          FOLDER="${{ github.event.inputs.folder_name }}"
          python pipeline/main.py --folder $FOLDER

      - name: Upload image artifact 上传最终选图和日志
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chose-images
          path: ${{ github.workspace }}/*.zip
          retention-days: 7 # 设置过期时间